name: MSBuild

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  SOLUTION_FILE_PATH: source/P4VFS.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Cache OpenSSL
      uses: actions/cache@v3
      with:
        path: |
          external/OpenSSL/[0-9]+*
          external/OpenSSL/.restored
        key: build-openssl-${{ hashFiles('external/OpenSSL/OpenSSL.Module.cs') }}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -clp:Summary -nologo -verbosity:m -restore -maxcpucount -p:Configuration=${{env.BUILD_CONFIGURATION}} -p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
